-- Stage 2B cannot represent strategy sources, transitions or operation kinds.
-- A downgrade intentionally removes only those Stage 2C records before the
-- narrower Stage 2B constraints are restored. The Stage 2B no-delete trigger
-- is disabled only for this migration-owned compatibility cleanup.
DELETE FROM clinical_ai_run_sources WHERE source_type IN('clinical_target','clinical_goal','goal_indicator','therapeutic_rationale','gira','gira_phase','therapeutic_approach_definition','therapeutic_technique_definition');
DELETE FROM clinical_longitudinal_transitions WHERE entity_type IN('target','goal','goal_indicator','therapeutic_rationale','gira','gira_phase');
ALTER TABLE clinical_diff_operations DISABLE TRIGGER clinical_diff_operations_no_delete;
DELETE FROM clinical_diff_operations WHERE operation_type IN(
'create_target','update_target','resolve_target','retire_target','create_goal','update_goal','activate_goal','pause_goal','achieve_goal','abandon_goal','create_goal_indicator','update_goal_indicator','link_indicator_evidence','link_indicator_event','create_therapeutic_rationale','update_therapeutic_rationale','create_gira','supersede_gira','activate_gira','pause_gira','complete_gira','create_gira_phase','update_gira_phase','activate_gira_phase','complete_gira_phase','pause_gira_phase');
ALTER TABLE clinical_diff_operations ENABLE TRIGGER clinical_diff_operations_no_delete;

CREATE OR REPLACE FUNCTION validate_clinical_ai_run_source() RETURNS trigger AS $$ DECLARE run_client UUID; BEGIN
SELECT client_id INTO run_client FROM clinical_ai_runs WHERE tenant_id=NEW.tenant_id AND id=NEW.ai_run_id;
IF NEW.source_type='formulation_snapshot' AND NOT EXISTS(SELECT 1 FROM clinical_formulation_snapshots WHERE tenant_id=NEW.tenant_id AND id=NEW.source_id AND status='approved' AND (NEW.source_version IS NULL OR version=NEW.source_version)) THEN RAISE EXCEPTION 'formulation snapshot source must be approved and tenant-local' USING ERRCODE='23503';
ELSIF NEW.source_type='formulation_anchor' AND NOT EXISTS(SELECT 1 FROM clinical_formulation_anchors a JOIN clinical_formulation_snapshots s ON s.tenant_id=a.tenant_id AND s.id=a.snapshot_id WHERE a.tenant_id=NEW.tenant_id AND a.id=NEW.source_id AND s.status='approved' AND (NEW.source_version IS NULL OR s.version=NEW.source_version)) THEN RAISE EXCEPTION 'formulation anchor source must belong to an approved tenant-local snapshot' USING ERRCODE='23503';
ELSIF NEW.source_type='session_report' AND NOT EXISTS(SELECT 1 FROM session_reports r JOIN clinical_sessions s ON s.tenant_id=r.tenant_id AND s.id=r.clinical_session_id WHERE r.tenant_id=NEW.tenant_id AND r.id=NEW.source_id AND r.status='approved' AND s.client_id=run_client AND (NEW.source_version IS NULL OR r.version=NEW.source_version)) THEN RAISE EXCEPTION 'session report source must be approved and tenant-local' USING ERRCODE='23503';
ELSIF NEW.source_type='clinical_evidence' AND NOT EXISTS(SELECT 1 FROM clinical_evidence WHERE tenant_id=NEW.tenant_id AND id=NEW.source_id AND client_id=run_client AND status='active' AND version=NEW.source_version) THEN RAISE EXCEPTION 'clinical evidence source must be active and tenant-local' USING ERRCODE='23503';
ELSIF NEW.source_type='clinical_event' AND NOT EXISTS(SELECT 1 FROM clinical_events WHERE tenant_id=NEW.tenant_id AND id=NEW.source_id AND client_id=run_client AND approval_status='approved' AND version=NEW.source_version) THEN RAISE EXCEPTION 'clinical event source must be approved and tenant-local' USING ERRCODE='23503';
ELSIF NEW.source_type='clinical_process' AND NOT EXISTS(SELECT 1 FROM clinical_processes WHERE tenant_id=NEW.tenant_id AND id=NEW.source_id AND client_id=run_client AND approval_status='approved' AND version=NEW.source_version) THEN RAISE EXCEPTION 'clinical process source must be approved and tenant-local' USING ERRCODE='23503';
ELSIF NEW.source_type='clinical_hypothesis' AND NOT EXISTS(SELECT 1 FROM clinical_hypotheses WHERE tenant_id=NEW.tenant_id AND id=NEW.source_id AND client_id=run_client AND approval_status='approved' AND version=NEW.source_version) THEN RAISE EXCEPTION 'clinical hypothesis source must be approved and tenant-local' USING ERRCODE='23503';END IF;RETURN NEW;END;$$ LANGUAGE plpgsql;
ALTER TABLE clinical_ai_run_sources DROP CONSTRAINT clinical_ai_run_sources_source_type_check;
ALTER TABLE clinical_ai_run_sources ADD CONSTRAINT clinical_ai_run_sources_source_type_check CHECK(source_type IN('formulation_snapshot','formulation_anchor','session_report','clinical_evidence','clinical_event','clinical_process','clinical_hypothesis'));
ALTER TABLE clinical_longitudinal_transitions DROP CONSTRAINT clinical_longitudinal_transitions_entity_type_check;
ALTER TABLE clinical_longitudinal_transitions ADD CONSTRAINT clinical_longitudinal_transitions_entity_type_check CHECK(entity_type IN('evidence','event','process','hypothesis'));
ALTER TABLE clinical_diff_operations DROP CONSTRAINT clinical_diff_operations_operation_type_check;
ALTER TABLE clinical_diff_operations ADD CONSTRAINT clinical_diff_operations_operation_type_check CHECK(operation_type IN('create_evidence','invalidate_evidence','create_event','approve_event','link_event_process','create_process','update_process','close_process','reopen_process','create_hypothesis','update_hypothesis','link_supporting_evidence','link_contradicting_evidence','strengthen_hypothesis','weaken_hypothesis','retire_hypothesis'));
DROP TABLE IF EXISTS gira_phase_indicators; DROP TABLE IF EXISTS gira_phase_rationales; DROP TABLE IF EXISTS gira_phase_goals; DROP TRIGGER IF EXISTS gira_phases_no_delete ON gira_phases; DROP TABLE IF EXISTS gira_phases;
DROP TABLE IF EXISTS gira_rationales; DROP TABLE IF EXISTS gira_goals; DROP TABLE IF EXISTS gira_targets; DROP TRIGGER IF EXISTS giras_no_delete ON giras; DROP TABLE IF EXISTS giras;
DROP TABLE IF EXISTS therapeutic_rationale_hypotheses; DROP TABLE IF EXISTS therapeutic_rationale_evidence; DROP TRIGGER IF EXISTS therapeutic_rationales_no_delete ON therapeutic_rationales; DROP TABLE IF EXISTS therapeutic_rationales;
DROP TABLE IF EXISTS clinical_indicator_events; DROP TABLE IF EXISTS clinical_indicator_evidence; DROP TRIGGER IF EXISTS clinical_goal_indicators_no_delete ON clinical_goal_indicators; DROP TABLE IF EXISTS clinical_goal_indicators;
DROP TRIGGER IF EXISTS clinical_goal_targets_preserve_requirement ON clinical_goal_targets; DROP TRIGGER IF EXISTS clinical_goals_require_target ON clinical_goals; DROP TABLE IF EXISTS clinical_goal_targets; DROP FUNCTION IF EXISTS ensure_approved_goal_target(); DROP TRIGGER IF EXISTS clinical_goals_no_delete ON clinical_goals; DROP TABLE IF EXISTS clinical_goals;
DROP TRIGGER IF EXISTS clinical_target_events_preserve_grounding ON clinical_target_events; DROP TRIGGER IF EXISTS clinical_target_hypotheses_preserve_grounding ON clinical_target_hypotheses; DROP TRIGGER IF EXISTS clinical_target_evidence_preserve_grounding ON clinical_target_evidence;
DROP TRIGGER IF EXISTS clinical_targets_require_grounding ON clinical_targets; DROP TABLE IF EXISTS clinical_target_events; DROP TABLE IF EXISTS clinical_target_hypotheses; DROP TABLE IF EXISTS clinical_target_evidence; DROP FUNCTION IF EXISTS ensure_approved_target_grounding(); DROP TRIGGER IF EXISTS clinical_targets_no_delete ON clinical_targets; DROP TABLE IF EXISTS clinical_targets;
DROP TRIGGER IF EXISTS therapeutic_techniques_no_delete ON therapeutic_technique_definitions; DROP TABLE IF EXISTS therapeutic_technique_definitions;
DROP TRIGGER IF EXISTS therapeutic_approaches_no_delete ON therapeutic_approach_definitions; DROP TABLE IF EXISTS therapeutic_approach_definitions;
