export const navigationItems = [
  {
    href: "/dashboard",
    label: "Panel",
    description: "Resumen operativo",
    icon: "dashboard",
    requiresAdmin: false,
  },
  {
    href: "/clients",
    label: "Pacientes",
    description: "Fichas y asignaciones",
    icon: "clients",
    requiresAdmin: false,
  },
  {
    href: "/appointments",
    label: "Citas",
    description: "Agenda y horarios",
    icon: "appointments",
    requiresAdmin: false,
  },
  {
		href: "/clinical-workspace",
		label: "Supervisor local",
		description: "Bloc de microprocesos",
		icon: "clinicalWorkspace",
		requiresAdmin: false,
	},
	{
		href: "/clinical-formulation",
		label: "Formulación",
		description: "Memoria longitudinal",
		icon: "clinicalFormulation",
		requiresAdmin: false,
	},
	{
		href: "/clinical-review",
		label: "Revisión posterior",
		description: "Análisis longitudinal",
		icon: "clinicalReview",
		requiresAdmin: false,
	},
	{
    href: "/session-notes",
    label: "Notas de sesión",
    description: "Registro clínico",
    icon: "sessionNotes",
    requiresAdmin: false,
  },
  {
    href: "/audit",
    label: "Auditoría",
    description: "Trazabilidad de cambios",
    icon: "audit",
    requiresAdmin: true,
  },
] as const;
